<?php

// =====================================================================
// FILE: src/EducationCatalog.php
// ---------------------------------------------------------------------
// GENERATED by tools/generate-education-catalog.js from
// assets/js/education-catalog.js — DO NOT hand-edit the data array.
// Regenerate after any catalog change:
//   node tools/generate-education-catalog.js
//
// Maps normalized fields of study to JobCatalog category ids, giving
// ScoreEngine deterministic education relevance when a profile's field
// matches (or contains) a catalog entry. Fields with an empty id list
// are recognized but carry no category signal (e.g. General Studies).
// =====================================================================

class EducationCatalog
{
    public const FIELD_MAP = [
        'accounting' => [9],
        'actuarial science' => [9,1],
        'aerospace engineering' => [17],
        'agricultural science' => [26,20],
        'agriculture' => [26],
        'animal science' => [26,20],
        'animation' => [4,21],
        'anthropology' => [20],
        'architecture' => [4,18,17],
        'artificial intelligence' => [1,0],
        'astronomy' => [20],
        'automotive technology' => [18,19],
        'aviation' => [12,17],
        'baking & pastry arts' => [22],
        'biochemistry' => [20,13],
        'biology' => [20,13],
        'biomedical engineering' => [17,13],
        'business administration' => [11,9],
        'business analytics' => [1,9],
        'business management' => [11],
        'carpentry' => [18],
        'chemical engineering' => [17,20],
        'chemistry' => [20],
        'civil engineering' => [17,18],
        'communications' => [6,21],
        'computer engineering' => [0,17],
        'computer information systems' => [2,0],
        'computer science' => [0,1,2],
        'construction management' => [18,11],
        'cosmetology' => [23],
        'counseling' => [14],
        'creative writing' => [21],
        'criminal justice' => [24,16],
        'criminology' => [24,16],
        'culinary arts' => [22],
        'curriculum & instruction' => [15],
        'cybersecurity' => [3,2],
        'data analytics' => [1],
        'data science' => [1],
        'dental hygiene' => [13],
        'dentistry' => [13],
        'early childhood education' => [15],
        'economics' => [9,1],
        'education' => [15],
        'educational leadership' => [15,11],
        'electrical engineering' => [17],
        'electrical technology' => [18],
        'elementary education' => [15],
        'emergency management' => [24],
        'emergency medical services' => [13,24],
        'english' => [21,15],
        'entrepreneurship' => [11,7],
        'environmental engineering' => [17,26],
        'environmental science' => [26,20],
        'exercise science' => [13],
        'fashion design' => [4,23],
        'film & media production' => [21,4],
        'finance' => [9],
        'fine arts' => [4],
        'fire science' => [24],
        'food science' => [26,20,19],
        'forensic science' => [20,24],
        'forestry' => [26],
        'game design & development' => [0,4],
        'general studies' => [],
        'genetics' => [20],
        'geography' => [20,24],
        'geology' => [20,26],
        'graphic design' => [4],
        'health administration' => [13,11],
        'history' => [15],
        'horticulture' => [26],
        'hospitality management' => [22,11],
        'human resource management' => [10],
        'human-computer interaction' => [4,0],
        'hvac technology' => [18],
        'industrial design' => [4,17],
        'industrial engineering' => [17,19,11],
        'information systems' => [2,11],
        'information technology' => [2],
        'instructional design' => [15,4],
        'interior design' => [4,25],
        'international business' => [11,7],
        'international relations' => [24],
        'journalism' => [21],
        'kinesiology' => [13],
        'law' => [16],
        'legal studies' => [16],
        'liberal arts' => [],
        'linguistics' => [15,1],
        'literature' => [21,15],
        'logistics & transportation' => [12],
        'machine learning' => [1],
        'machining & cnc' => [19,18],
        'marine biology' => [20,26],
        'marketing' => [6,7],
        'marriage & family therapy' => [14],
        'materials science & engineering' => [17,20],
        'mathematics' => [1,20,9],
        'mechanical engineering' => [17,19],
        'medical laboratory science' => [13,20],
        'medicine' => [13],
        'microbiology' => [20,13],
        'military science' => [24],
        'modern languages' => [15],
        'music' => [21],
        'music performance' => [21],
        'network administration' => [2],
        'neuroscience' => [20,13],
        'nuclear engineering' => [17,20],
        'nursing' => [13],
        'nutrition & dietetics' => [13],
        'occupational therapy' => [13],
        'paralegal studies' => [16],
        'petroleum engineering' => [17],
        'pharmacy' => [13],
        'philosophy' => [15],
        'photography' => [4,21],
        'physical therapy' => [13],
        'physics' => [20,17],
        'plumbing technology' => [18],
        'political science' => [24,16],
        'pre-medicine' => [13,20],
        'project management' => [5,11],
        'psychology' => [14,10],
        'public administration' => [24,11],
        'public health' => [13,24],
        'public policy' => [24],
        'public relations' => [6],
        'radiologic technology' => [13],
        'real estate' => [25],
        'religious studies' => [15],
        'robotics engineering' => [17,0],
        'sales management' => [7],
        'secondary education' => [15],
        'social work' => [14],
        'sociology' => [14,24],
        'software engineering' => [0],
        'special education' => [15,14],
        'speech-language pathology' => [13,14],
        'sport management' => [11,6],
        'statistics' => [1,20],
        'structural engineering' => [17,18],
        'studio art' => [4],
        'substance abuse counseling' => [14],
        'supply chain management' => [12,11],
        'sustainability studies' => [26],
        'theater arts' => [21],
        'urban planning' => [24,25],
        'ux design' => [4,0],
        'veterinary medicine' => [13,26],
        'veterinary technology' => [13,26],
        'web development' => [0,4],
        'welding technology' => [18,19],
        'wildlife & fisheries' => [26,20],
    ];

    /**
     * Category ids for a field-of-study string, or null when the text
     * doesn't correspond to any catalog field. Tries an exact match on
     * the normalized text first, then containment (so "BS in Computer
     * Science" still resolves). Longest catalog names are checked first
     * so "Computer Engineering" wins over "Engineering"-style overlaps.
     */
    public static function categoriesForField(string $text): ?array
    {
        $norm = strtolower(trim($text));
        if ($norm === '') return null;
        if (isset(self::FIELD_MAP[$norm])) return self::FIELD_MAP[$norm];

        static $byLength = null;
        if ($byLength === null) {
            $byLength = array_keys(self::FIELD_MAP);
            usort($byLength, fn($a, $b) => strlen($b) <=> strlen($a));
        }
        foreach ($byLength as $name) {
            if (str_contains($norm, $name)) return self::FIELD_MAP[$name];
        }
        return null;
    }
}
